In [1]:
import pandas as pd
import numpy as np

In [36]:
data1 = pd.read_excel('data1_연령대별_체육활동_비율.xlsx', encoding='utf-8', index_col='연령')
data2 = pd.read_excel('data2_행정동별_시설.xlsx', encoding='utf-8',index_col='행정동')
# data3 = pd.read_excel('data3_서울시_행정동별_연령별_인구.xlsx', encoding='utf-8',index_col='행정동')
data4 = pd.read_excel('data4_행정동_인접행렬.xlsx', encoding='utf-8',index_col='행정동')

In [54]:
data3 = pd.read_excel('data3_서울시_행정동별_연령별_인구.xlsx', encoding='utf-8',index_col='행정동')

In [55]:
data1_array = data1.values
data2_array = data2.values
data3_array = data3.values
data4_array = data4.values

In [104]:
data2

게이트볼  골프        농구        배구      배드민턴  빙상  수영  암벽등반  야구  에어로빅  \
행정동                                                                           
가락1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
가락2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
가락본동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
가리봉동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
가산동             0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
가양1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
가양2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
가양3동            0   0  0.000000  0.000000  1.000000   0   1     0   0   0.0   
가회동             0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
갈현1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
갈현2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
강일동             0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
개봉1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
개봉2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
개봉3동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
개포1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
개포2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
개포4동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
거여1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
거여2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
고덕1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
고덕2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
고척1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
고척2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
공덕동             0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
공릉1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
공릉2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
공항동             0   0  0.000000  0.000000  0.000000   0   2     0   0   0.0   
광장동             0   2  1.500000  0.500000  1.000000   0   2     0   0   1.0   
광희동             0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
교남동             0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
구로1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
구로2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
구로3동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
구로4동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
구로5동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
구산동             0   0  0.000000  0.000000  1.000000   0   0     0   0   0.0   
구의1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
구의2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
구의3동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
군자동             0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
금호1가동           0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
금호2.3가동         0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
금호4가동           0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
길동              0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
길음1동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
길음2동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
낙성대동            0   0  0.000000  0.000000  0.000000   0   0     0   0   0.0   
난곡동             0   0  0.000000  0.000000  0.000000   0   0    

In [56]:
data3_array

array([[2210, 3642, 5266, ..., 3868, 2818, 1324],
       [3810, 4887, 5085, ..., 5444, 3747, 2221],
       [2125, 4430, 5016, ..., 4936, 3274, 2019],
       ...,
       [ 870, 2850, 2005, ..., 2113, 1608, 1593],
       [2271, 5087, 3223, ..., 3586, 2862, 2418],
       [2341, 5204, 5032, ..., 5235, 3832, 3780]], dtype=int64)

In [98]:
pd.set_option("display.max_rows", 999)

In [100]:
data2

array([[0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.33, ..., 0.33, 0.  , 1.  ]])

In [79]:
one_two = np.dot(data1_array, data2_array.T)

In [91]:
one_two.T[200]

array([44.70353098, 37.96109993, 29.02777778, 22.58503401, 17.53378378,
       10.81272085,  8.02315964])

In [58]:
three_one = np.dot(data3_array, data1_array)

In [78]:
three_one

array([[  6847.82079759,  73493.83446057,  48320.41232482, ...,
         31704.57046752,  17461.82515163, 340354.92651629],
       [  9890.03188135,  97806.35712154,  73040.4035158 , ...,
         42308.84015202,  22589.1717812 , 435007.81591909],
       [  8801.05523159,  82817.45895984,  49936.16978895, ...,
         34626.09266286,  19276.2475666 , 376931.98524484],
       ...,
       [  5204.57627565,  37791.93875181,  24237.09650699, ...,
         16365.24546407,   9603.56283422, 189253.29960881],
       [  8572.12157387,  66304.01447513,  51736.81606231, ...,
         30447.14830601,  16953.81769954, 334017.00931511],
       [ 12417.84971573,  94986.59312064,  55866.03944075, ...,
         38138.29210973,  22497.8780254 , 431300.43502042]])

In [59]:
final = np.dot(three_one, data2_array.T)

In [61]:
final.shape

(424, 424)

In [62]:
final_list = [] 
for i in range(424):
    for j in range(424):
        if i == j :
            final_list.append(final[i][j])

In [64]:
final_list

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 189967.14992550117,
 0.0,
 0.0,
 0.0,
 20608.336744648048,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 106547.65490262385,
 0.0,
 0.0,
 0.0,
 301160.7027840007,
 1685960.3556490466,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 231260.2656435005,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 226150.65166751348,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 12071.039788325681,
 0.0,
 0.0,
 40544.49687708453,
 0.0,
 0.0,
 107479.89074809827,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1011207.2625796185,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 192218.19472294295,
 0.0,
 0.0,
 68792.75657481715,
 70415.9339904387,
 94776.33151182494,
 0.0,
 149575.50104243204,
 0.0,
 159971.56549228224,
 0.0,
 0.0,
 0.0,
 473066.21134957764,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 843600.2232588179,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 27608.834555464604,
 0.0,


In [66]:
data_final_1 = data3

In [67]:
data_final_1['page1'] = final_list

In [69]:
data_final_1_1 = data_final_1.copy()

In [70]:
data_final_1_1 = pd.DataFrame(data_final_1['page1'])

In [74]:
data_final_1_1['page1'].value_counts()

0.000000e+00    336
1.617258e+05      1
3.067439e+05      1
1.855258e+05      1
2.060834e+04      1
1.317257e+06      1
1.590885e+06      1
2.343612e+05      1
1.255417e+04      1
6.294673e+05      1
2.145671e+04      1
1.123181e+05      1
9.547130e+04      1
6.084761e+05      1
4.854249e+05      1
1.771548e+05      1
3.886438e+05      1
1.470583e+05      1
1.599716e+05      1
3.107934e+05      1
1.727641e+04      1
1.204972e+05      1
2.261507e+05      1
1.940715e+05      1
3.559402e+06      1
2.419304e+04      1
1.685960e+06      1
1.899671e+05      1
4.700383e+05      1
9.477633e+04      1
               ... 
2.390867e+03      1
2.845550e+05      1
2.923475e+05      1
1.065477e+05      1
7.611387e+03      1
1.011207e+06      1
9.608945e+04      1
1.637576e+04      1
8.436002e+05      1
4.054450e+04      1
7.041593e+04      1
1.783391e+05      1
1.447431e+05      1
1.207104e+04      1
4.138933e+06      1
1.778374e+05      1
1.089275e+05      1
1.478626e+05      1
1.472207e+04      1


In [75]:
424-336

88